import { Inter } from "next/font/google";
import "../../globals.css";
import DisabledCopy from "@/Components/Utilites/DisabledCopy/DisabledCopy";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Envobyte",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="">{children}</div>
      </body>
    </html>
  );
}
