import ServicesPageContent from "@/Components/PagesComponents/ServicesPageContent/ServicesPageContent";
import React from "react";

export const metadata = {
  title: "Envobyte || Services",
  description: "Generated by create next app",
};

const ServicesPage = () => {
  return (
    <div>
      <ServicesPageContent />
    </div>
  );
};

export default ServicesPage;
