import { Inter } from "next/font/google";
import "../globals.css";
import { Toaster } from "react-hot-toast";
import DashBoardSideNav from "@/Components/Dashboard/DashBoardSideNav";
import DashBoardNav from "@/Components/Dashboard/DashBoardNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Envobyte Ltd",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link
        rel="icon"
        href="https://i.ibb.co/nM2nH6n/android-chrome-256x256.png"
        sizes="any"
      />

      <body className={inter.className}>

        <div className="bg-[#FCFCFC]">
          <div>
            <div className="w-full flex">
              <DashBoardSideNav height="100vh" />
              <div className="w-full ">
                <DashBoardNav title="dashboard" />
                {children}
              </div>
            </div>
          </div>
        </div>

        <Toaster />



      </body>
    </html>
  );
}
