import ServiceDetails from "@/Components/PagesComponents/ServiceDetails/ServiceDetails";
import {
  singeServiceDetails,
  singleService_package,
  singleSliderPageDetails,
} from "@/config/apis";

export const metadata = {
  title: "Single Service || Envobyte",
  description: "Generated by create next app",
};

async function serviceData(id) {
  console.log(id);
  const res = await fetch(`${singeServiceDetails}/${id}`, {
    next: { revalidate: 10 },
  });

  if (!res.ok) {
    throw new Error("Failed to fetch data");
  }
  return res.json();
}
async function slidersData(id) {
  const res = await fetch(`${singleSliderPageDetails}/${id}`, {
    next: { revalidate: 10 },
  });

  if (!res.ok) {
    throw new Error("Failed to fetch data");
  }
  return res.json();
}
async function packageData(id) {
  const res = await fetch(`${singleService_package}/${id}`, {
    next: { revalidate: 10 },
  });

  if (!res.ok) {
    throw new Error("Failed to fetch data");
  }
  return res.json();
}

const SinglePage = async ({ params }) => {
  const service = await serviceData(params.id);
  const sliders = await slidersData(params.id);
  const packages = await packageData(params.id);

  return (
    <>
      <ServiceDetails service={service} sliders={sliders} packages={packages} />
    </>
  );
};

export default SinglePage;
