import Container from "@/Components/Container/Container";
import PortfolioPage from "@/Components/PagesComponents/PortfolioPage/PortfolioPage";
export const metadata = {
  title: "Envobyte || Portfolio ",
  description: "Generated by create next app",
};

const Portfolio = () => {
  return (
    <div>
      <Container>
        <PortfolioPage />
      </Container>
    </div>
  );
};

export default Portfolio;
