import AboutUsContent from "@/Components/PagesComponents/AboutUsContent/AboutUsContent";
import React from "react";

export const metadata = {
  title: "Envobyte || About Us",
  description: "Generated by create next app",
};

const AboutUsPage = () => {
  return (
    <>
      <AboutUsContent />
    </>
  );
};

export default AboutUsPage;
